[project]
name = "evraz-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.5",
    "asyncpg>=0.31.0",
    "fastapi>=0.139.2",
    "langgraph>=1.2.9",
    "openai>=2.45.0",
    "sqlalchemy>=2.0.51",
    "loguru>=0.7.3",
    "pydantic-settings>=2.14.2",
    "openpyxl>=3.1.5",
    "pandas>=3.0.3",
    "pgvector>=0.5.0",
    "uvicorn[standard]>=0.27",
    "psycopg2>=2.9.12",
    "dotenv>=0.9.9",
    "openpyxl>=3.1.5",
    "python-multipart>=0.0.18",
    "rank-bm25>=0.2.2",
    "numpy>=1.26.0",
]

