"""updated

Revision ID: 38a9b3b78105
Revises: 5cd4e6e3ed49
Create Date: 2026-07-22 19:42:11.537351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a9b3b78105'
down_revision: Union[str, Sequence[str], None] = '5cd4e6e3ed49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_column_metadata_data_type'), table_name='column_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_column_metadata_data_type'), 'column_metadata', ['data_type'], unique=False)
    # ### end Alembic commands ###
