"""updated

Revision ID: 9577c3f54b77
Revises: 38a9b3b78105
Create Date: 2026-07-22 19:52:07.080841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9577c3f54b77'
down_revision: Union[str, Sequence[str], None] = '38a9b3b78105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_column_metadata_data_type', 'column_metadata', ['data_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_column_metadata_data_type', table_name='column_metadata')
    # ### end Alembic commands ###
