"""add column_embeddings table

Revision ID: e52c9527c01e
Revises: e76d64c605aa
Create Date: 2026-07-22 14:44:21.689011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector

# revision identifiers, used by Alembic.
revision: str = 'e52c9527c01e'
down_revision: Union[str, Sequence[str], None] = 'e76d64c605aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['column_metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_embeddings_column_id'), 'column_embeddings', ['column_id'], unique=True)
    op.create_index(op.f('ix_column_embeddings_id'), 'column_embeddings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_column_embeddings_id'), table_name='column_embeddings')
    op.drop_index(op.f('ix_column_embeddings_column_id'), table_name='column_embeddings')
    op.drop_table('column_embeddings')
    # ### end Alembic commands ###
