"""initial schema

Revision ID: e76d64c605aa
Revises: 
Create Date: 2026-07-21 20:26:16.365317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'e76d64c605aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('total_sheets', sa.Integer(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('total_cells', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_file_hash'), 'files', ['file_hash'], unique=True)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index('ix_files_status', 'files', ['status'], unique=False)
    op.create_index('ix_files_uploaded_at', 'files', ['uploaded_at'], unique=False)
    op.create_table('query_embedding_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_query_embedding_cache_hash', 'query_embedding_cache', ['query_hash'], unique=False)
    op.create_index(op.f('ix_query_embedding_cache_id'), 'query_embedding_cache', ['id'], unique=False)
    op.create_index(op.f('ix_query_embedding_cache_query_hash'), 'query_embedding_cache', ['query_hash'], unique=True)
    op.create_table('query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=36), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('sql_query', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('trace', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_query_logs_created_at', 'query_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_query_logs_id'), 'query_logs', ['id'], unique=False)
    op.create_index('ix_query_logs_request_id', 'query_logs', ['request_id'], unique=False)
    op.create_index('ix_query_logs_status', 'query_logs', ['status'], unique=False)
    op.create_index(op.f('ix_query_logs_user_id'), 'query_logs', ['user_id'], unique=False)
    op.create_table('sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('sheet_index', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('col_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sheets_file_id', 'sheets', ['file_id'], unique=False)
    op.create_index(op.f('ix_sheets_id'), 'sheets', ['id'], unique=False)
    op.create_index(op.f('ix_sheets_normalized_name'), 'sheets', ['normalized_name'], unique=False)
    op.create_index('ix_sheets_original_name', 'sheets', ['original_name'], unique=False)
    op.create_table('cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('row_num', sa.Integer(), nullable=False),
    sa.Column('col_index', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Integer(), nullable=True),
    sa.Column('value_date', sa.DateTime(), nullable=True),
    sa.Column('is_error', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cells_id'), 'cells', ['id'], unique=False)
    op.create_index('ix_cells_sheet_id', 'cells', ['sheet_id'], unique=False)
    op.create_index('ix_cells_value_number', 'cells', ['value_number'], unique=False)
    op.create_table('column_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('col_index', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sample_values', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_column_metadata_data_type', 'column_metadata', ['data_type'], unique=False)
    op.create_index(op.f('ix_column_metadata_id'), 'column_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_column_metadata_normalized_name'), 'column_metadata', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_column_metadata_sheet_id'), 'column_metadata', ['sheet_id'], unique=False)
    op.create_table('sheet_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sheet_embeddings_id'), 'sheet_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_sheet_embeddings_sheet_id'), 'sheet_embeddings', ['sheet_id'], unique=True)
    op.create_table('column_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['column_metadata.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_column_embeddings_column_id'), 'column_embeddings', ['column_id'], unique=True)
    op.create_index(op.f('ix_column_embeddings_id'), 'column_embeddings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_column_embeddings_id'), table_name='column_embeddings')
    op.drop_index(op.f('ix_column_embeddings_column_id'), table_name='column_embeddings')
    op.drop_table('column_embeddings')
    op.drop_index(op.f('ix_sheet_embeddings_sheet_id'), table_name='sheet_embeddings')
    op.drop_index(op.f('ix_sheet_embeddings_id'), table_name='sheet_embeddings')
    op.drop_table('sheet_embeddings')
    op.drop_index(op.f('ix_column_metadata_sheet_id'), table_name='column_metadata')
    op.drop_index(op.f('ix_column_metadata_normalized_name'), table_name='column_metadata')
    op.drop_index(op.f('ix_column_metadata_id'), table_name='column_metadata')
    op.drop_index('ix_column_metadata_data_type', table_name='column_metadata')
    op.drop_table('column_metadata')
    op.drop_index('ix_cells_value_number', table_name='cells')
    op.drop_index('ix_cells_sheet_id', table_name='cells')
    op.drop_index(op.f('ix_cells_id'), table_name='cells')
    op.drop_table('cells')
    op.drop_index('ix_sheets_original_name', table_name='sheets')
    op.drop_index(op.f('ix_sheets_normalized_name'), table_name='sheets')
    op.drop_index(op.f('ix_sheets_id'), table_name='sheets')
    op.drop_index('ix_sheets_file_id', table_name='sheets')
    op.drop_table('sheets')
    op.drop_index(op.f('ix_query_logs_user_id'), table_name='query_logs')
    op.drop_index('ix_query_logs_status', table_name='query_logs')
    op.drop_index('ix_query_logs_request_id', table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_id'), table_name='query_logs')
    op.drop_index('ix_query_logs_created_at', table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index(op.f('ix_query_embedding_cache_query_hash'), table_name='query_embedding_cache')
    op.drop_index(op.f('ix_query_embedding_cache_id'), table_name='query_embedding_cache')
    op.drop_index('ix_query_embedding_cache_hash', table_name='query_embedding_cache')
    op.drop_table('query_embedding_cache')
    op.drop_index('ix_files_uploaded_at', table_name='files')
    op.drop_index('ix_files_status', table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_file_hash'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
